// Stub for the cmake-generated cuda_cmake_macros.h
// On ROCm Windows builds, this file is not generated by CMake.
// Define the macros it normally exports so ATen/cuda headers compile.
#pragma once

// Mark ATen CUDA API as dllimport (we link against the pre-built torch DLL).
#ifdef _WIN32
#define TORCH_CUDA_CPP_API __declspec(dllimport)
#define TORCH_CUDA_CU_API __declspec(dllimport)
#define TORCH_CUDA_BUILD_SHARED_LIBS
#else
#define TORCH_CUDA_CPP_API
#define TORCH_CUDA_CU_API
#endif
